#! /bin/bash
printf "%s\n" "$(tput bold)$(date) ${BASH_SOURCE[0]}$(tput sgr0)"

# generated by geo_writer.f08.
#  2020-05-09 23:05:02

# sequence of operations
# 1. bring in geometry file for specific elevation
# 2. run Mercury MoM - pipe into outputs folder
# 3. move Mercury MoM results file to outputs folder
# 4. remove geometry file

# sequence of operations
# 1. bring in geometry file for specific elevation
# 2. run Mercury MoM - pipe into outputs folder
# 3. move Mercury MoM results file to outputs folder
# 4. remove geometry file

# directory structure:

# ./
#   -- bin
#        MMoM_4.1.12
#        elevation-sweep.sh
#   -- inputs
#        facet file
#        geo files
#        materials library (empty file)
#   -- outputs
#        MoM results *.4112.txt
#        MoM run log *.out

# counts steps in batch process
export counter=0
export SECONDS=0
function new_step(){
    export counter=$((counter+1))
    export subcounter=0
    echo ""; echo ""
    echo "Step ${counter}: ${1}"
}
function sub_step(){
    subcounter=$((subcounter+1))
    echo ""
    echo "  Substep ${counter}.${subcounter}: ${1}"
}

# # # shared files
echo 'cp ../inputs/PTW-Materials.lib .'
      cp ../inputs/PTW-Materials.lib .
echo 'cp ../inputs/PTW.facet .'
      cp ../inputs/PTW.facet .

export ticks=${SECONDS}
new_step 'elevation angle = -89 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n089.geo .'
          cp ../inputs/PTW-elev-0n089.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n089.geo > ../outputs/PTW-elev-0n089.out'
          ./MMoM_4.1.12 PTW-elev-0n089.geo > ../outputs/PTW-elev-0n089.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n089.geo'
          rm PTW-elev-0n089.geo

echo ""
echo "time used to run PTW-elev-0n089.geo = $((SECONDS-ticks)) s"


new_step 'clear shared files'
sub_step 'rm PTW-Materials.lib'
          rm PTW-Materials.lib
sub_step 'rm PTW.facet'
          rm PTW.facet
sub_step 'rm -r tempDir/'
          rm -r tempDir/

echo ""
echo "time used = ${SECONDS} s"
date

