#! /bin/bash
printf "%s\n" "$(tput bold)$(date) ${BASH_SOURCE[0]}$(tput sgr0)"

# generated by geo_writer.f08.
#  2020-05-09 23:05:02

# sequence of operations
# 1. bring in geometry file for specific elevation
# 2. run Mercury MoM - pipe into outputs folder
# 3. move Mercury MoM results file to outputs folder
# 4. remove geometry file

# sequence of operations
# 1. bring in geometry file for specific elevation
# 2. run Mercury MoM - pipe into outputs folder
# 3. move Mercury MoM results file to outputs folder
# 4. remove geometry file

# directory structure:

# ./
#   -- bin
#        MMoM_4.1.12
#        elevation-sweep.sh
#   -- inputs
#        facet file
#        geo files
#        materials library (empty file)
#   -- outputs
#        MoM results *.4112.txt
#        MoM run log *.out

# counts steps in batch process
export counter=0
export SECONDS=0
function new_step(){
    export counter=$((counter+1))
    export subcounter=0
    echo ""; echo ""
    echo "Step ${counter}: ${1}"
}
function sub_step(){
    subcounter=$((subcounter+1))
    echo ""
    echo "  Substep ${counter}.${subcounter}: ${1}"
}

# # # shared files
echo 'cp ../inputs/PTW-Materials.lib .'
      cp ../inputs/PTW-Materials.lib .
echo 'cp ../inputs/PTW.facet .'
      cp ../inputs/PTW.facet .

export ticks=${SECONDS}
new_step 'elevation angle = -89 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n089.geo .'
          cp ../inputs/PTW-elev-0n089.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n089.geo > ../outputs/PTW-elev-0n089.out'
          ./MMoM_4.1.12 PTW-elev-0n089.geo > ../outputs/PTW-elev-0n089.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n089.geo'
          rm PTW-elev-0n089.geo

echo ""
echo "time used to run PTW-elev-0n089.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -88 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n088.geo .'
          cp ../inputs/PTW-elev-0n088.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n088.geo > ../outputs/PTW-elev-0n088.out'
          ./MMoM_4.1.12 PTW-elev-0n088.geo > ../outputs/PTW-elev-0n088.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n088.geo'
          rm PTW-elev-0n088.geo

echo ""
echo "time used to run PTW-elev-0n088.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -87 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n087.geo .'
          cp ../inputs/PTW-elev-0n087.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n087.geo > ../outputs/PTW-elev-0n087.out'
          ./MMoM_4.1.12 PTW-elev-0n087.geo > ../outputs/PTW-elev-0n087.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n087.geo'
          rm PTW-elev-0n087.geo

echo ""
echo "time used to run PTW-elev-0n087.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -86 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n086.geo .'
          cp ../inputs/PTW-elev-0n086.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n086.geo > ../outputs/PTW-elev-0n086.out'
          ./MMoM_4.1.12 PTW-elev-0n086.geo > ../outputs/PTW-elev-0n086.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n086.geo'
          rm PTW-elev-0n086.geo

echo ""
echo "time used to run PTW-elev-0n086.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -85 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n085.geo .'
          cp ../inputs/PTW-elev-0n085.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n085.geo > ../outputs/PTW-elev-0n085.out'
          ./MMoM_4.1.12 PTW-elev-0n085.geo > ../outputs/PTW-elev-0n085.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n085.geo'
          rm PTW-elev-0n085.geo

echo ""
echo "time used to run PTW-elev-0n085.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -84 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n084.geo .'
          cp ../inputs/PTW-elev-0n084.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n084.geo > ../outputs/PTW-elev-0n084.out'
          ./MMoM_4.1.12 PTW-elev-0n084.geo > ../outputs/PTW-elev-0n084.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n084.geo'
          rm PTW-elev-0n084.geo

echo ""
echo "time used to run PTW-elev-0n084.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -83 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n083.geo .'
          cp ../inputs/PTW-elev-0n083.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n083.geo > ../outputs/PTW-elev-0n083.out'
          ./MMoM_4.1.12 PTW-elev-0n083.geo > ../outputs/PTW-elev-0n083.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n083.geo'
          rm PTW-elev-0n083.geo

echo ""
echo "time used to run PTW-elev-0n083.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -82 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n082.geo .'
          cp ../inputs/PTW-elev-0n082.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n082.geo > ../outputs/PTW-elev-0n082.out'
          ./MMoM_4.1.12 PTW-elev-0n082.geo > ../outputs/PTW-elev-0n082.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n082.geo'
          rm PTW-elev-0n082.geo

echo ""
echo "time used to run PTW-elev-0n082.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -81 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n081.geo .'
          cp ../inputs/PTW-elev-0n081.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n081.geo > ../outputs/PTW-elev-0n081.out'
          ./MMoM_4.1.12 PTW-elev-0n081.geo > ../outputs/PTW-elev-0n081.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n081.geo'
          rm PTW-elev-0n081.geo

echo ""
echo "time used to run PTW-elev-0n081.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -80 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n080.geo .'
          cp ../inputs/PTW-elev-0n080.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n080.geo > ../outputs/PTW-elev-0n080.out'
          ./MMoM_4.1.12 PTW-elev-0n080.geo > ../outputs/PTW-elev-0n080.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n080.geo'
          rm PTW-elev-0n080.geo

echo ""
echo "time used to run PTW-elev-0n080.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -79 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n079.geo .'
          cp ../inputs/PTW-elev-0n079.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n079.geo > ../outputs/PTW-elev-0n079.out'
          ./MMoM_4.1.12 PTW-elev-0n079.geo > ../outputs/PTW-elev-0n079.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n079.geo'
          rm PTW-elev-0n079.geo

echo ""
echo "time used to run PTW-elev-0n079.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -78 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n078.geo .'
          cp ../inputs/PTW-elev-0n078.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n078.geo > ../outputs/PTW-elev-0n078.out'
          ./MMoM_4.1.12 PTW-elev-0n078.geo > ../outputs/PTW-elev-0n078.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n078.geo'
          rm PTW-elev-0n078.geo

echo ""
echo "time used to run PTW-elev-0n078.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -77 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n077.geo .'
          cp ../inputs/PTW-elev-0n077.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n077.geo > ../outputs/PTW-elev-0n077.out'
          ./MMoM_4.1.12 PTW-elev-0n077.geo > ../outputs/PTW-elev-0n077.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n077.geo'
          rm PTW-elev-0n077.geo

echo ""
echo "time used to run PTW-elev-0n077.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -76 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n076.geo .'
          cp ../inputs/PTW-elev-0n076.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n076.geo > ../outputs/PTW-elev-0n076.out'
          ./MMoM_4.1.12 PTW-elev-0n076.geo > ../outputs/PTW-elev-0n076.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n076.geo'
          rm PTW-elev-0n076.geo

echo ""
echo "time used to run PTW-elev-0n076.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -75 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n075.geo .'
          cp ../inputs/PTW-elev-0n075.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n075.geo > ../outputs/PTW-elev-0n075.out'
          ./MMoM_4.1.12 PTW-elev-0n075.geo > ../outputs/PTW-elev-0n075.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n075.geo'
          rm PTW-elev-0n075.geo

echo ""
echo "time used to run PTW-elev-0n075.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -74 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n074.geo .'
          cp ../inputs/PTW-elev-0n074.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n074.geo > ../outputs/PTW-elev-0n074.out'
          ./MMoM_4.1.12 PTW-elev-0n074.geo > ../outputs/PTW-elev-0n074.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n074.geo'
          rm PTW-elev-0n074.geo

echo ""
echo "time used to run PTW-elev-0n074.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -73 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n073.geo .'
          cp ../inputs/PTW-elev-0n073.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n073.geo > ../outputs/PTW-elev-0n073.out'
          ./MMoM_4.1.12 PTW-elev-0n073.geo > ../outputs/PTW-elev-0n073.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n073.geo'
          rm PTW-elev-0n073.geo

echo ""
echo "time used to run PTW-elev-0n073.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -72 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n072.geo .'
          cp ../inputs/PTW-elev-0n072.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n072.geo > ../outputs/PTW-elev-0n072.out'
          ./MMoM_4.1.12 PTW-elev-0n072.geo > ../outputs/PTW-elev-0n072.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n072.geo'
          rm PTW-elev-0n072.geo

echo ""
echo "time used to run PTW-elev-0n072.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -71 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n071.geo .'
          cp ../inputs/PTW-elev-0n071.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n071.geo > ../outputs/PTW-elev-0n071.out'
          ./MMoM_4.1.12 PTW-elev-0n071.geo > ../outputs/PTW-elev-0n071.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n071.geo'
          rm PTW-elev-0n071.geo

echo ""
echo "time used to run PTW-elev-0n071.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -70 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n070.geo .'
          cp ../inputs/PTW-elev-0n070.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n070.geo > ../outputs/PTW-elev-0n070.out'
          ./MMoM_4.1.12 PTW-elev-0n070.geo > ../outputs/PTW-elev-0n070.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n070.geo'
          rm PTW-elev-0n070.geo

echo ""
echo "time used to run PTW-elev-0n070.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -69 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n069.geo .'
          cp ../inputs/PTW-elev-0n069.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n069.geo > ../outputs/PTW-elev-0n069.out'
          ./MMoM_4.1.12 PTW-elev-0n069.geo > ../outputs/PTW-elev-0n069.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n069.geo'
          rm PTW-elev-0n069.geo

echo ""
echo "time used to run PTW-elev-0n069.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -68 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n068.geo .'
          cp ../inputs/PTW-elev-0n068.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n068.geo > ../outputs/PTW-elev-0n068.out'
          ./MMoM_4.1.12 PTW-elev-0n068.geo > ../outputs/PTW-elev-0n068.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n068.geo'
          rm PTW-elev-0n068.geo

echo ""
echo "time used to run PTW-elev-0n068.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -67 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n067.geo .'
          cp ../inputs/PTW-elev-0n067.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n067.geo > ../outputs/PTW-elev-0n067.out'
          ./MMoM_4.1.12 PTW-elev-0n067.geo > ../outputs/PTW-elev-0n067.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n067.geo'
          rm PTW-elev-0n067.geo

echo ""
echo "time used to run PTW-elev-0n067.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -66 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n066.geo .'
          cp ../inputs/PTW-elev-0n066.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n066.geo > ../outputs/PTW-elev-0n066.out'
          ./MMoM_4.1.12 PTW-elev-0n066.geo > ../outputs/PTW-elev-0n066.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n066.geo'
          rm PTW-elev-0n066.geo

echo ""
echo "time used to run PTW-elev-0n066.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -65 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n065.geo .'
          cp ../inputs/PTW-elev-0n065.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n065.geo > ../outputs/PTW-elev-0n065.out'
          ./MMoM_4.1.12 PTW-elev-0n065.geo > ../outputs/PTW-elev-0n065.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n065.geo'
          rm PTW-elev-0n065.geo

echo ""
echo "time used to run PTW-elev-0n065.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -64 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n064.geo .'
          cp ../inputs/PTW-elev-0n064.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n064.geo > ../outputs/PTW-elev-0n064.out'
          ./MMoM_4.1.12 PTW-elev-0n064.geo > ../outputs/PTW-elev-0n064.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n064.geo'
          rm PTW-elev-0n064.geo

echo ""
echo "time used to run PTW-elev-0n064.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -63 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n063.geo .'
          cp ../inputs/PTW-elev-0n063.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n063.geo > ../outputs/PTW-elev-0n063.out'
          ./MMoM_4.1.12 PTW-elev-0n063.geo > ../outputs/PTW-elev-0n063.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n063.geo'
          rm PTW-elev-0n063.geo

echo ""
echo "time used to run PTW-elev-0n063.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -62 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n062.geo .'
          cp ../inputs/PTW-elev-0n062.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n062.geo > ../outputs/PTW-elev-0n062.out'
          ./MMoM_4.1.12 PTW-elev-0n062.geo > ../outputs/PTW-elev-0n062.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n062.geo'
          rm PTW-elev-0n062.geo

echo ""
echo "time used to run PTW-elev-0n062.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -61 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n061.geo .'
          cp ../inputs/PTW-elev-0n061.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n061.geo > ../outputs/PTW-elev-0n061.out'
          ./MMoM_4.1.12 PTW-elev-0n061.geo > ../outputs/PTW-elev-0n061.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n061.geo'
          rm PTW-elev-0n061.geo

echo ""
echo "time used to run PTW-elev-0n061.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -60 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n060.geo .'
          cp ../inputs/PTW-elev-0n060.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n060.geo > ../outputs/PTW-elev-0n060.out'
          ./MMoM_4.1.12 PTW-elev-0n060.geo > ../outputs/PTW-elev-0n060.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n060.geo'
          rm PTW-elev-0n060.geo

echo ""
echo "time used to run PTW-elev-0n060.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -59 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n059.geo .'
          cp ../inputs/PTW-elev-0n059.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n059.geo > ../outputs/PTW-elev-0n059.out'
          ./MMoM_4.1.12 PTW-elev-0n059.geo > ../outputs/PTW-elev-0n059.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n059.geo'
          rm PTW-elev-0n059.geo

echo ""
echo "time used to run PTW-elev-0n059.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -58 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n058.geo .'
          cp ../inputs/PTW-elev-0n058.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n058.geo > ../outputs/PTW-elev-0n058.out'
          ./MMoM_4.1.12 PTW-elev-0n058.geo > ../outputs/PTW-elev-0n058.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n058.geo'
          rm PTW-elev-0n058.geo

echo ""
echo "time used to run PTW-elev-0n058.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -57 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n057.geo .'
          cp ../inputs/PTW-elev-0n057.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n057.geo > ../outputs/PTW-elev-0n057.out'
          ./MMoM_4.1.12 PTW-elev-0n057.geo > ../outputs/PTW-elev-0n057.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n057.geo'
          rm PTW-elev-0n057.geo

echo ""
echo "time used to run PTW-elev-0n057.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -56 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n056.geo .'
          cp ../inputs/PTW-elev-0n056.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n056.geo > ../outputs/PTW-elev-0n056.out'
          ./MMoM_4.1.12 PTW-elev-0n056.geo > ../outputs/PTW-elev-0n056.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n056.geo'
          rm PTW-elev-0n056.geo

echo ""
echo "time used to run PTW-elev-0n056.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -55 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n055.geo .'
          cp ../inputs/PTW-elev-0n055.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n055.geo > ../outputs/PTW-elev-0n055.out'
          ./MMoM_4.1.12 PTW-elev-0n055.geo > ../outputs/PTW-elev-0n055.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n055.geo'
          rm PTW-elev-0n055.geo

echo ""
echo "time used to run PTW-elev-0n055.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -54 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n054.geo .'
          cp ../inputs/PTW-elev-0n054.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n054.geo > ../outputs/PTW-elev-0n054.out'
          ./MMoM_4.1.12 PTW-elev-0n054.geo > ../outputs/PTW-elev-0n054.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n054.geo'
          rm PTW-elev-0n054.geo

echo ""
echo "time used to run PTW-elev-0n054.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -53 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n053.geo .'
          cp ../inputs/PTW-elev-0n053.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n053.geo > ../outputs/PTW-elev-0n053.out'
          ./MMoM_4.1.12 PTW-elev-0n053.geo > ../outputs/PTW-elev-0n053.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n053.geo'
          rm PTW-elev-0n053.geo

echo ""
echo "time used to run PTW-elev-0n053.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -52 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n052.geo .'
          cp ../inputs/PTW-elev-0n052.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n052.geo > ../outputs/PTW-elev-0n052.out'
          ./MMoM_4.1.12 PTW-elev-0n052.geo > ../outputs/PTW-elev-0n052.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n052.geo'
          rm PTW-elev-0n052.geo

echo ""
echo "time used to run PTW-elev-0n052.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -51 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n051.geo .'
          cp ../inputs/PTW-elev-0n051.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n051.geo > ../outputs/PTW-elev-0n051.out'
          ./MMoM_4.1.12 PTW-elev-0n051.geo > ../outputs/PTW-elev-0n051.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n051.geo'
          rm PTW-elev-0n051.geo

echo ""
echo "time used to run PTW-elev-0n051.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -50 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n050.geo .'
          cp ../inputs/PTW-elev-0n050.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n050.geo > ../outputs/PTW-elev-0n050.out'
          ./MMoM_4.1.12 PTW-elev-0n050.geo > ../outputs/PTW-elev-0n050.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n050.geo'
          rm PTW-elev-0n050.geo

echo ""
echo "time used to run PTW-elev-0n050.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -49 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n049.geo .'
          cp ../inputs/PTW-elev-0n049.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n049.geo > ../outputs/PTW-elev-0n049.out'
          ./MMoM_4.1.12 PTW-elev-0n049.geo > ../outputs/PTW-elev-0n049.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n049.geo'
          rm PTW-elev-0n049.geo

echo ""
echo "time used to run PTW-elev-0n049.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -48 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n048.geo .'
          cp ../inputs/PTW-elev-0n048.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n048.geo > ../outputs/PTW-elev-0n048.out'
          ./MMoM_4.1.12 PTW-elev-0n048.geo > ../outputs/PTW-elev-0n048.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n048.geo'
          rm PTW-elev-0n048.geo

echo ""
echo "time used to run PTW-elev-0n048.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -47 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n047.geo .'
          cp ../inputs/PTW-elev-0n047.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n047.geo > ../outputs/PTW-elev-0n047.out'
          ./MMoM_4.1.12 PTW-elev-0n047.geo > ../outputs/PTW-elev-0n047.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n047.geo'
          rm PTW-elev-0n047.geo

echo ""
echo "time used to run PTW-elev-0n047.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -46 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n046.geo .'
          cp ../inputs/PTW-elev-0n046.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n046.geo > ../outputs/PTW-elev-0n046.out'
          ./MMoM_4.1.12 PTW-elev-0n046.geo > ../outputs/PTW-elev-0n046.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n046.geo'
          rm PTW-elev-0n046.geo

echo ""
echo "time used to run PTW-elev-0n046.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -45 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n045.geo .'
          cp ../inputs/PTW-elev-0n045.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n045.geo > ../outputs/PTW-elev-0n045.out'
          ./MMoM_4.1.12 PTW-elev-0n045.geo > ../outputs/PTW-elev-0n045.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n045.geo'
          rm PTW-elev-0n045.geo

echo ""
echo "time used to run PTW-elev-0n045.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -44 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n044.geo .'
          cp ../inputs/PTW-elev-0n044.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n044.geo > ../outputs/PTW-elev-0n044.out'
          ./MMoM_4.1.12 PTW-elev-0n044.geo > ../outputs/PTW-elev-0n044.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n044.geo'
          rm PTW-elev-0n044.geo

echo ""
echo "time used to run PTW-elev-0n044.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -43 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n043.geo .'
          cp ../inputs/PTW-elev-0n043.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n043.geo > ../outputs/PTW-elev-0n043.out'
          ./MMoM_4.1.12 PTW-elev-0n043.geo > ../outputs/PTW-elev-0n043.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n043.geo'
          rm PTW-elev-0n043.geo

echo ""
echo "time used to run PTW-elev-0n043.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -42 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n042.geo .'
          cp ../inputs/PTW-elev-0n042.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n042.geo > ../outputs/PTW-elev-0n042.out'
          ./MMoM_4.1.12 PTW-elev-0n042.geo > ../outputs/PTW-elev-0n042.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n042.geo'
          rm PTW-elev-0n042.geo

echo ""
echo "time used to run PTW-elev-0n042.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -41 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n041.geo .'
          cp ../inputs/PTW-elev-0n041.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n041.geo > ../outputs/PTW-elev-0n041.out'
          ./MMoM_4.1.12 PTW-elev-0n041.geo > ../outputs/PTW-elev-0n041.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n041.geo'
          rm PTW-elev-0n041.geo

echo ""
echo "time used to run PTW-elev-0n041.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -40 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n040.geo .'
          cp ../inputs/PTW-elev-0n040.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n040.geo > ../outputs/PTW-elev-0n040.out'
          ./MMoM_4.1.12 PTW-elev-0n040.geo > ../outputs/PTW-elev-0n040.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n040.geo'
          rm PTW-elev-0n040.geo

echo ""
echo "time used to run PTW-elev-0n040.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -39 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n039.geo .'
          cp ../inputs/PTW-elev-0n039.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n039.geo > ../outputs/PTW-elev-0n039.out'
          ./MMoM_4.1.12 PTW-elev-0n039.geo > ../outputs/PTW-elev-0n039.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n039.geo'
          rm PTW-elev-0n039.geo

echo ""
echo "time used to run PTW-elev-0n039.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -38 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n038.geo .'
          cp ../inputs/PTW-elev-0n038.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n038.geo > ../outputs/PTW-elev-0n038.out'
          ./MMoM_4.1.12 PTW-elev-0n038.geo > ../outputs/PTW-elev-0n038.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n038.geo'
          rm PTW-elev-0n038.geo

echo ""
echo "time used to run PTW-elev-0n038.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -37 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n037.geo .'
          cp ../inputs/PTW-elev-0n037.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n037.geo > ../outputs/PTW-elev-0n037.out'
          ./MMoM_4.1.12 PTW-elev-0n037.geo > ../outputs/PTW-elev-0n037.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n037.geo'
          rm PTW-elev-0n037.geo

echo ""
echo "time used to run PTW-elev-0n037.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -36 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n036.geo .'
          cp ../inputs/PTW-elev-0n036.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n036.geo > ../outputs/PTW-elev-0n036.out'
          ./MMoM_4.1.12 PTW-elev-0n036.geo > ../outputs/PTW-elev-0n036.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n036.geo'
          rm PTW-elev-0n036.geo

echo ""
echo "time used to run PTW-elev-0n036.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -35 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n035.geo .'
          cp ../inputs/PTW-elev-0n035.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n035.geo > ../outputs/PTW-elev-0n035.out'
          ./MMoM_4.1.12 PTW-elev-0n035.geo > ../outputs/PTW-elev-0n035.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n035.geo'
          rm PTW-elev-0n035.geo

echo ""
echo "time used to run PTW-elev-0n035.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -34 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n034.geo .'
          cp ../inputs/PTW-elev-0n034.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n034.geo > ../outputs/PTW-elev-0n034.out'
          ./MMoM_4.1.12 PTW-elev-0n034.geo > ../outputs/PTW-elev-0n034.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n034.geo'
          rm PTW-elev-0n034.geo

echo ""
echo "time used to run PTW-elev-0n034.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -33 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n033.geo .'
          cp ../inputs/PTW-elev-0n033.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n033.geo > ../outputs/PTW-elev-0n033.out'
          ./MMoM_4.1.12 PTW-elev-0n033.geo > ../outputs/PTW-elev-0n033.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n033.geo'
          rm PTW-elev-0n033.geo

echo ""
echo "time used to run PTW-elev-0n033.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -32 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n032.geo .'
          cp ../inputs/PTW-elev-0n032.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n032.geo > ../outputs/PTW-elev-0n032.out'
          ./MMoM_4.1.12 PTW-elev-0n032.geo > ../outputs/PTW-elev-0n032.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n032.geo'
          rm PTW-elev-0n032.geo

echo ""
echo "time used to run PTW-elev-0n032.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -31 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n031.geo .'
          cp ../inputs/PTW-elev-0n031.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n031.geo > ../outputs/PTW-elev-0n031.out'
          ./MMoM_4.1.12 PTW-elev-0n031.geo > ../outputs/PTW-elev-0n031.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n031.geo'
          rm PTW-elev-0n031.geo

echo ""
echo "time used to run PTW-elev-0n031.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -30 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n030.geo .'
          cp ../inputs/PTW-elev-0n030.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n030.geo > ../outputs/PTW-elev-0n030.out'
          ./MMoM_4.1.12 PTW-elev-0n030.geo > ../outputs/PTW-elev-0n030.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n030.geo'
          rm PTW-elev-0n030.geo

echo ""
echo "time used to run PTW-elev-0n030.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -29 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n029.geo .'
          cp ../inputs/PTW-elev-0n029.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n029.geo > ../outputs/PTW-elev-0n029.out'
          ./MMoM_4.1.12 PTW-elev-0n029.geo > ../outputs/PTW-elev-0n029.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n029.geo'
          rm PTW-elev-0n029.geo

echo ""
echo "time used to run PTW-elev-0n029.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -28 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n028.geo .'
          cp ../inputs/PTW-elev-0n028.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n028.geo > ../outputs/PTW-elev-0n028.out'
          ./MMoM_4.1.12 PTW-elev-0n028.geo > ../outputs/PTW-elev-0n028.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n028.geo'
          rm PTW-elev-0n028.geo

echo ""
echo "time used to run PTW-elev-0n028.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -27 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n027.geo .'
          cp ../inputs/PTW-elev-0n027.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n027.geo > ../outputs/PTW-elev-0n027.out'
          ./MMoM_4.1.12 PTW-elev-0n027.geo > ../outputs/PTW-elev-0n027.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n027.geo'
          rm PTW-elev-0n027.geo

echo ""
echo "time used to run PTW-elev-0n027.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -26 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n026.geo .'
          cp ../inputs/PTW-elev-0n026.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n026.geo > ../outputs/PTW-elev-0n026.out'
          ./MMoM_4.1.12 PTW-elev-0n026.geo > ../outputs/PTW-elev-0n026.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n026.geo'
          rm PTW-elev-0n026.geo

echo ""
echo "time used to run PTW-elev-0n026.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -25 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n025.geo .'
          cp ../inputs/PTW-elev-0n025.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n025.geo > ../outputs/PTW-elev-0n025.out'
          ./MMoM_4.1.12 PTW-elev-0n025.geo > ../outputs/PTW-elev-0n025.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n025.geo'
          rm PTW-elev-0n025.geo

echo ""
echo "time used to run PTW-elev-0n025.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -24 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n024.geo .'
          cp ../inputs/PTW-elev-0n024.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n024.geo > ../outputs/PTW-elev-0n024.out'
          ./MMoM_4.1.12 PTW-elev-0n024.geo > ../outputs/PTW-elev-0n024.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n024.geo'
          rm PTW-elev-0n024.geo

echo ""
echo "time used to run PTW-elev-0n024.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -23 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n023.geo .'
          cp ../inputs/PTW-elev-0n023.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n023.geo > ../outputs/PTW-elev-0n023.out'
          ./MMoM_4.1.12 PTW-elev-0n023.geo > ../outputs/PTW-elev-0n023.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n023.geo'
          rm PTW-elev-0n023.geo

echo ""
echo "time used to run PTW-elev-0n023.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -22 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n022.geo .'
          cp ../inputs/PTW-elev-0n022.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n022.geo > ../outputs/PTW-elev-0n022.out'
          ./MMoM_4.1.12 PTW-elev-0n022.geo > ../outputs/PTW-elev-0n022.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n022.geo'
          rm PTW-elev-0n022.geo

echo ""
echo "time used to run PTW-elev-0n022.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -21 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n021.geo .'
          cp ../inputs/PTW-elev-0n021.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n021.geo > ../outputs/PTW-elev-0n021.out'
          ./MMoM_4.1.12 PTW-elev-0n021.geo > ../outputs/PTW-elev-0n021.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n021.geo'
          rm PTW-elev-0n021.geo

echo ""
echo "time used to run PTW-elev-0n021.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -20 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n020.geo .'
          cp ../inputs/PTW-elev-0n020.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n020.geo > ../outputs/PTW-elev-0n020.out'
          ./MMoM_4.1.12 PTW-elev-0n020.geo > ../outputs/PTW-elev-0n020.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n020.geo'
          rm PTW-elev-0n020.geo

echo ""
echo "time used to run PTW-elev-0n020.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -19 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n019.geo .'
          cp ../inputs/PTW-elev-0n019.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n019.geo > ../outputs/PTW-elev-0n019.out'
          ./MMoM_4.1.12 PTW-elev-0n019.geo > ../outputs/PTW-elev-0n019.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n019.geo'
          rm PTW-elev-0n019.geo

echo ""
echo "time used to run PTW-elev-0n019.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -18 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n018.geo .'
          cp ../inputs/PTW-elev-0n018.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n018.geo > ../outputs/PTW-elev-0n018.out'
          ./MMoM_4.1.12 PTW-elev-0n018.geo > ../outputs/PTW-elev-0n018.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n018.geo'
          rm PTW-elev-0n018.geo

echo ""
echo "time used to run PTW-elev-0n018.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -17 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n017.geo .'
          cp ../inputs/PTW-elev-0n017.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n017.geo > ../outputs/PTW-elev-0n017.out'
          ./MMoM_4.1.12 PTW-elev-0n017.geo > ../outputs/PTW-elev-0n017.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n017.geo'
          rm PTW-elev-0n017.geo

echo ""
echo "time used to run PTW-elev-0n017.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -16 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n016.geo .'
          cp ../inputs/PTW-elev-0n016.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n016.geo > ../outputs/PTW-elev-0n016.out'
          ./MMoM_4.1.12 PTW-elev-0n016.geo > ../outputs/PTW-elev-0n016.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n016.geo'
          rm PTW-elev-0n016.geo

echo ""
echo "time used to run PTW-elev-0n016.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -15 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n015.geo .'
          cp ../inputs/PTW-elev-0n015.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n015.geo > ../outputs/PTW-elev-0n015.out'
          ./MMoM_4.1.12 PTW-elev-0n015.geo > ../outputs/PTW-elev-0n015.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n015.geo'
          rm PTW-elev-0n015.geo

echo ""
echo "time used to run PTW-elev-0n015.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -14 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n014.geo .'
          cp ../inputs/PTW-elev-0n014.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n014.geo > ../outputs/PTW-elev-0n014.out'
          ./MMoM_4.1.12 PTW-elev-0n014.geo > ../outputs/PTW-elev-0n014.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n014.geo'
          rm PTW-elev-0n014.geo

echo ""
echo "time used to run PTW-elev-0n014.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -13 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n013.geo .'
          cp ../inputs/PTW-elev-0n013.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n013.geo > ../outputs/PTW-elev-0n013.out'
          ./MMoM_4.1.12 PTW-elev-0n013.geo > ../outputs/PTW-elev-0n013.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n013.geo'
          rm PTW-elev-0n013.geo

echo ""
echo "time used to run PTW-elev-0n013.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -12 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n012.geo .'
          cp ../inputs/PTW-elev-0n012.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n012.geo > ../outputs/PTW-elev-0n012.out'
          ./MMoM_4.1.12 PTW-elev-0n012.geo > ../outputs/PTW-elev-0n012.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n012.geo'
          rm PTW-elev-0n012.geo

echo ""
echo "time used to run PTW-elev-0n012.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -11 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n011.geo .'
          cp ../inputs/PTW-elev-0n011.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n011.geo > ../outputs/PTW-elev-0n011.out'
          ./MMoM_4.1.12 PTW-elev-0n011.geo > ../outputs/PTW-elev-0n011.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n011.geo'
          rm PTW-elev-0n011.geo

echo ""
echo "time used to run PTW-elev-0n011.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -10 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n010.geo .'
          cp ../inputs/PTW-elev-0n010.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n010.geo > ../outputs/PTW-elev-0n010.out'
          ./MMoM_4.1.12 PTW-elev-0n010.geo > ../outputs/PTW-elev-0n010.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n010.geo'
          rm PTW-elev-0n010.geo

echo ""
echo "time used to run PTW-elev-0n010.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -9 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n009.geo .'
          cp ../inputs/PTW-elev-0n009.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n009.geo > ../outputs/PTW-elev-0n009.out'
          ./MMoM_4.1.12 PTW-elev-0n009.geo > ../outputs/PTW-elev-0n009.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n009.geo'
          rm PTW-elev-0n009.geo

echo ""
echo "time used to run PTW-elev-0n009.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -8 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n008.geo .'
          cp ../inputs/PTW-elev-0n008.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n008.geo > ../outputs/PTW-elev-0n008.out'
          ./MMoM_4.1.12 PTW-elev-0n008.geo > ../outputs/PTW-elev-0n008.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n008.geo'
          rm PTW-elev-0n008.geo

echo ""
echo "time used to run PTW-elev-0n008.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -7 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n007.geo .'
          cp ../inputs/PTW-elev-0n007.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n007.geo > ../outputs/PTW-elev-0n007.out'
          ./MMoM_4.1.12 PTW-elev-0n007.geo > ../outputs/PTW-elev-0n007.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n007.geo'
          rm PTW-elev-0n007.geo

echo ""
echo "time used to run PTW-elev-0n007.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -6 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n006.geo .'
          cp ../inputs/PTW-elev-0n006.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n006.geo > ../outputs/PTW-elev-0n006.out'
          ./MMoM_4.1.12 PTW-elev-0n006.geo > ../outputs/PTW-elev-0n006.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n006.geo'
          rm PTW-elev-0n006.geo

echo ""
echo "time used to run PTW-elev-0n006.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -5 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n005.geo .'
          cp ../inputs/PTW-elev-0n005.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n005.geo > ../outputs/PTW-elev-0n005.out'
          ./MMoM_4.1.12 PTW-elev-0n005.geo > ../outputs/PTW-elev-0n005.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n005.geo'
          rm PTW-elev-0n005.geo

echo ""
echo "time used to run PTW-elev-0n005.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -4 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n004.geo .'
          cp ../inputs/PTW-elev-0n004.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n004.geo > ../outputs/PTW-elev-0n004.out'
          ./MMoM_4.1.12 PTW-elev-0n004.geo > ../outputs/PTW-elev-0n004.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n004.geo'
          rm PTW-elev-0n004.geo

echo ""
echo "time used to run PTW-elev-0n004.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -3 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n003.geo .'
          cp ../inputs/PTW-elev-0n003.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n003.geo > ../outputs/PTW-elev-0n003.out'
          ./MMoM_4.1.12 PTW-elev-0n003.geo > ../outputs/PTW-elev-0n003.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n003.geo'
          rm PTW-elev-0n003.geo

echo ""
echo "time used to run PTW-elev-0n003.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -2 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n002.geo .'
          cp ../inputs/PTW-elev-0n002.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n002.geo > ../outputs/PTW-elev-0n002.out'
          ./MMoM_4.1.12 PTW-elev-0n002.geo > ../outputs/PTW-elev-0n002.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n002.geo'
          rm PTW-elev-0n002.geo

echo ""
echo "time used to run PTW-elev-0n002.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -1 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0n001.geo .'
          cp ../inputs/PTW-elev-0n001.geo .

sub_step './MMoM_4.1.12 PTW-elev-0n001.geo > ../outputs/PTW-elev-0n001.out'
          ./MMoM_4.1.12 PTW-elev-0n001.geo > ../outputs/PTW-elev-0n001.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0n001.geo'
          rm PTW-elev-0n001.geo

echo ""
echo "time used to run PTW-elev-0n001.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 0 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p000.geo .'
          cp ../inputs/PTW-elev-0p000.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p000.geo > ../outputs/PTW-elev-0p000.out'
          ./MMoM_4.1.12 PTW-elev-0p000.geo > ../outputs/PTW-elev-0p000.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p000.geo'
          rm PTW-elev-0p000.geo

echo ""
echo "time used to run PTW-elev-0p000.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 1 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p001.geo .'
          cp ../inputs/PTW-elev-0p001.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p001.geo > ../outputs/PTW-elev-0p001.out'
          ./MMoM_4.1.12 PTW-elev-0p001.geo > ../outputs/PTW-elev-0p001.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p001.geo'
          rm PTW-elev-0p001.geo

echo ""
echo "time used to run PTW-elev-0p001.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 2 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p002.geo .'
          cp ../inputs/PTW-elev-0p002.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p002.geo > ../outputs/PTW-elev-0p002.out'
          ./MMoM_4.1.12 PTW-elev-0p002.geo > ../outputs/PTW-elev-0p002.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p002.geo'
          rm PTW-elev-0p002.geo

echo ""
echo "time used to run PTW-elev-0p002.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 3 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p003.geo .'
          cp ../inputs/PTW-elev-0p003.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p003.geo > ../outputs/PTW-elev-0p003.out'
          ./MMoM_4.1.12 PTW-elev-0p003.geo > ../outputs/PTW-elev-0p003.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p003.geo'
          rm PTW-elev-0p003.geo

echo ""
echo "time used to run PTW-elev-0p003.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 4 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p004.geo .'
          cp ../inputs/PTW-elev-0p004.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p004.geo > ../outputs/PTW-elev-0p004.out'
          ./MMoM_4.1.12 PTW-elev-0p004.geo > ../outputs/PTW-elev-0p004.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p004.geo'
          rm PTW-elev-0p004.geo

echo ""
echo "time used to run PTW-elev-0p004.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 5 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p005.geo .'
          cp ../inputs/PTW-elev-0p005.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p005.geo > ../outputs/PTW-elev-0p005.out'
          ./MMoM_4.1.12 PTW-elev-0p005.geo > ../outputs/PTW-elev-0p005.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p005.geo'
          rm PTW-elev-0p005.geo

echo ""
echo "time used to run PTW-elev-0p005.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 6 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p006.geo .'
          cp ../inputs/PTW-elev-0p006.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p006.geo > ../outputs/PTW-elev-0p006.out'
          ./MMoM_4.1.12 PTW-elev-0p006.geo > ../outputs/PTW-elev-0p006.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p006.geo'
          rm PTW-elev-0p006.geo

echo ""
echo "time used to run PTW-elev-0p006.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 7 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p007.geo .'
          cp ../inputs/PTW-elev-0p007.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p007.geo > ../outputs/PTW-elev-0p007.out'
          ./MMoM_4.1.12 PTW-elev-0p007.geo > ../outputs/PTW-elev-0p007.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p007.geo'
          rm PTW-elev-0p007.geo

echo ""
echo "time used to run PTW-elev-0p007.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 8 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p008.geo .'
          cp ../inputs/PTW-elev-0p008.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p008.geo > ../outputs/PTW-elev-0p008.out'
          ./MMoM_4.1.12 PTW-elev-0p008.geo > ../outputs/PTW-elev-0p008.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p008.geo'
          rm PTW-elev-0p008.geo

echo ""
echo "time used to run PTW-elev-0p008.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 9 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p009.geo .'
          cp ../inputs/PTW-elev-0p009.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p009.geo > ../outputs/PTW-elev-0p009.out'
          ./MMoM_4.1.12 PTW-elev-0p009.geo > ../outputs/PTW-elev-0p009.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p009.geo'
          rm PTW-elev-0p009.geo

echo ""
echo "time used to run PTW-elev-0p009.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 10 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p010.geo .'
          cp ../inputs/PTW-elev-0p010.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p010.geo > ../outputs/PTW-elev-0p010.out'
          ./MMoM_4.1.12 PTW-elev-0p010.geo > ../outputs/PTW-elev-0p010.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p010.geo'
          rm PTW-elev-0p010.geo

echo ""
echo "time used to run PTW-elev-0p010.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 11 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p011.geo .'
          cp ../inputs/PTW-elev-0p011.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p011.geo > ../outputs/PTW-elev-0p011.out'
          ./MMoM_4.1.12 PTW-elev-0p011.geo > ../outputs/PTW-elev-0p011.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p011.geo'
          rm PTW-elev-0p011.geo

echo ""
echo "time used to run PTW-elev-0p011.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 12 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p012.geo .'
          cp ../inputs/PTW-elev-0p012.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p012.geo > ../outputs/PTW-elev-0p012.out'
          ./MMoM_4.1.12 PTW-elev-0p012.geo > ../outputs/PTW-elev-0p012.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p012.geo'
          rm PTW-elev-0p012.geo

echo ""
echo "time used to run PTW-elev-0p012.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 13 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p013.geo .'
          cp ../inputs/PTW-elev-0p013.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p013.geo > ../outputs/PTW-elev-0p013.out'
          ./MMoM_4.1.12 PTW-elev-0p013.geo > ../outputs/PTW-elev-0p013.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p013.geo'
          rm PTW-elev-0p013.geo

echo ""
echo "time used to run PTW-elev-0p013.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 14 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p014.geo .'
          cp ../inputs/PTW-elev-0p014.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p014.geo > ../outputs/PTW-elev-0p014.out'
          ./MMoM_4.1.12 PTW-elev-0p014.geo > ../outputs/PTW-elev-0p014.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p014.geo'
          rm PTW-elev-0p014.geo

echo ""
echo "time used to run PTW-elev-0p014.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 15 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p015.geo .'
          cp ../inputs/PTW-elev-0p015.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p015.geo > ../outputs/PTW-elev-0p015.out'
          ./MMoM_4.1.12 PTW-elev-0p015.geo > ../outputs/PTW-elev-0p015.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p015.geo'
          rm PTW-elev-0p015.geo

echo ""
echo "time used to run PTW-elev-0p015.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 16 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p016.geo .'
          cp ../inputs/PTW-elev-0p016.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p016.geo > ../outputs/PTW-elev-0p016.out'
          ./MMoM_4.1.12 PTW-elev-0p016.geo > ../outputs/PTW-elev-0p016.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p016.geo'
          rm PTW-elev-0p016.geo

echo ""
echo "time used to run PTW-elev-0p016.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 17 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p017.geo .'
          cp ../inputs/PTW-elev-0p017.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p017.geo > ../outputs/PTW-elev-0p017.out'
          ./MMoM_4.1.12 PTW-elev-0p017.geo > ../outputs/PTW-elev-0p017.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p017.geo'
          rm PTW-elev-0p017.geo

echo ""
echo "time used to run PTW-elev-0p017.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 18 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p018.geo .'
          cp ../inputs/PTW-elev-0p018.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p018.geo > ../outputs/PTW-elev-0p018.out'
          ./MMoM_4.1.12 PTW-elev-0p018.geo > ../outputs/PTW-elev-0p018.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p018.geo'
          rm PTW-elev-0p018.geo

echo ""
echo "time used to run PTW-elev-0p018.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 19 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p019.geo .'
          cp ../inputs/PTW-elev-0p019.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p019.geo > ../outputs/PTW-elev-0p019.out'
          ./MMoM_4.1.12 PTW-elev-0p019.geo > ../outputs/PTW-elev-0p019.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p019.geo'
          rm PTW-elev-0p019.geo

echo ""
echo "time used to run PTW-elev-0p019.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 20 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p020.geo .'
          cp ../inputs/PTW-elev-0p020.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p020.geo > ../outputs/PTW-elev-0p020.out'
          ./MMoM_4.1.12 PTW-elev-0p020.geo > ../outputs/PTW-elev-0p020.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p020.geo'
          rm PTW-elev-0p020.geo

echo ""
echo "time used to run PTW-elev-0p020.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 21 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p021.geo .'
          cp ../inputs/PTW-elev-0p021.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p021.geo > ../outputs/PTW-elev-0p021.out'
          ./MMoM_4.1.12 PTW-elev-0p021.geo > ../outputs/PTW-elev-0p021.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p021.geo'
          rm PTW-elev-0p021.geo

echo ""
echo "time used to run PTW-elev-0p021.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 22 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p022.geo .'
          cp ../inputs/PTW-elev-0p022.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p022.geo > ../outputs/PTW-elev-0p022.out'
          ./MMoM_4.1.12 PTW-elev-0p022.geo > ../outputs/PTW-elev-0p022.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p022.geo'
          rm PTW-elev-0p022.geo

echo ""
echo "time used to run PTW-elev-0p022.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 23 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p023.geo .'
          cp ../inputs/PTW-elev-0p023.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p023.geo > ../outputs/PTW-elev-0p023.out'
          ./MMoM_4.1.12 PTW-elev-0p023.geo > ../outputs/PTW-elev-0p023.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p023.geo'
          rm PTW-elev-0p023.geo

echo ""
echo "time used to run PTW-elev-0p023.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 24 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p024.geo .'
          cp ../inputs/PTW-elev-0p024.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p024.geo > ../outputs/PTW-elev-0p024.out'
          ./MMoM_4.1.12 PTW-elev-0p024.geo > ../outputs/PTW-elev-0p024.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p024.geo'
          rm PTW-elev-0p024.geo

echo ""
echo "time used to run PTW-elev-0p024.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 25 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p025.geo .'
          cp ../inputs/PTW-elev-0p025.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p025.geo > ../outputs/PTW-elev-0p025.out'
          ./MMoM_4.1.12 PTW-elev-0p025.geo > ../outputs/PTW-elev-0p025.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p025.geo'
          rm PTW-elev-0p025.geo

echo ""
echo "time used to run PTW-elev-0p025.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 26 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p026.geo .'
          cp ../inputs/PTW-elev-0p026.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p026.geo > ../outputs/PTW-elev-0p026.out'
          ./MMoM_4.1.12 PTW-elev-0p026.geo > ../outputs/PTW-elev-0p026.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p026.geo'
          rm PTW-elev-0p026.geo

echo ""
echo "time used to run PTW-elev-0p026.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 27 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p027.geo .'
          cp ../inputs/PTW-elev-0p027.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p027.geo > ../outputs/PTW-elev-0p027.out'
          ./MMoM_4.1.12 PTW-elev-0p027.geo > ../outputs/PTW-elev-0p027.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p027.geo'
          rm PTW-elev-0p027.geo

echo ""
echo "time used to run PTW-elev-0p027.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 28 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p028.geo .'
          cp ../inputs/PTW-elev-0p028.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p028.geo > ../outputs/PTW-elev-0p028.out'
          ./MMoM_4.1.12 PTW-elev-0p028.geo > ../outputs/PTW-elev-0p028.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p028.geo'
          rm PTW-elev-0p028.geo

echo ""
echo "time used to run PTW-elev-0p028.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 29 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p029.geo .'
          cp ../inputs/PTW-elev-0p029.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p029.geo > ../outputs/PTW-elev-0p029.out'
          ./MMoM_4.1.12 PTW-elev-0p029.geo > ../outputs/PTW-elev-0p029.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p029.geo'
          rm PTW-elev-0p029.geo

echo ""
echo "time used to run PTW-elev-0p029.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 30 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p030.geo .'
          cp ../inputs/PTW-elev-0p030.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p030.geo > ../outputs/PTW-elev-0p030.out'
          ./MMoM_4.1.12 PTW-elev-0p030.geo > ../outputs/PTW-elev-0p030.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p030.geo'
          rm PTW-elev-0p030.geo

echo ""
echo "time used to run PTW-elev-0p030.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 31 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p031.geo .'
          cp ../inputs/PTW-elev-0p031.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p031.geo > ../outputs/PTW-elev-0p031.out'
          ./MMoM_4.1.12 PTW-elev-0p031.geo > ../outputs/PTW-elev-0p031.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p031.geo'
          rm PTW-elev-0p031.geo

echo ""
echo "time used to run PTW-elev-0p031.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 32 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p032.geo .'
          cp ../inputs/PTW-elev-0p032.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p032.geo > ../outputs/PTW-elev-0p032.out'
          ./MMoM_4.1.12 PTW-elev-0p032.geo > ../outputs/PTW-elev-0p032.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p032.geo'
          rm PTW-elev-0p032.geo

echo ""
echo "time used to run PTW-elev-0p032.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 33 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p033.geo .'
          cp ../inputs/PTW-elev-0p033.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p033.geo > ../outputs/PTW-elev-0p033.out'
          ./MMoM_4.1.12 PTW-elev-0p033.geo > ../outputs/PTW-elev-0p033.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p033.geo'
          rm PTW-elev-0p033.geo

echo ""
echo "time used to run PTW-elev-0p033.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 34 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p034.geo .'
          cp ../inputs/PTW-elev-0p034.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p034.geo > ../outputs/PTW-elev-0p034.out'
          ./MMoM_4.1.12 PTW-elev-0p034.geo > ../outputs/PTW-elev-0p034.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p034.geo'
          rm PTW-elev-0p034.geo

echo ""
echo "time used to run PTW-elev-0p034.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 35 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p035.geo .'
          cp ../inputs/PTW-elev-0p035.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p035.geo > ../outputs/PTW-elev-0p035.out'
          ./MMoM_4.1.12 PTW-elev-0p035.geo > ../outputs/PTW-elev-0p035.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p035.geo'
          rm PTW-elev-0p035.geo

echo ""
echo "time used to run PTW-elev-0p035.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 36 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p036.geo .'
          cp ../inputs/PTW-elev-0p036.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p036.geo > ../outputs/PTW-elev-0p036.out'
          ./MMoM_4.1.12 PTW-elev-0p036.geo > ../outputs/PTW-elev-0p036.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p036.geo'
          rm PTW-elev-0p036.geo

echo ""
echo "time used to run PTW-elev-0p036.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 37 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p037.geo .'
          cp ../inputs/PTW-elev-0p037.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p037.geo > ../outputs/PTW-elev-0p037.out'
          ./MMoM_4.1.12 PTW-elev-0p037.geo > ../outputs/PTW-elev-0p037.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p037.geo'
          rm PTW-elev-0p037.geo

echo ""
echo "time used to run PTW-elev-0p037.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 38 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p038.geo .'
          cp ../inputs/PTW-elev-0p038.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p038.geo > ../outputs/PTW-elev-0p038.out'
          ./MMoM_4.1.12 PTW-elev-0p038.geo > ../outputs/PTW-elev-0p038.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p038.geo'
          rm PTW-elev-0p038.geo

echo ""
echo "time used to run PTW-elev-0p038.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 39 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p039.geo .'
          cp ../inputs/PTW-elev-0p039.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p039.geo > ../outputs/PTW-elev-0p039.out'
          ./MMoM_4.1.12 PTW-elev-0p039.geo > ../outputs/PTW-elev-0p039.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p039.geo'
          rm PTW-elev-0p039.geo

echo ""
echo "time used to run PTW-elev-0p039.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 40 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p040.geo .'
          cp ../inputs/PTW-elev-0p040.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p040.geo > ../outputs/PTW-elev-0p040.out'
          ./MMoM_4.1.12 PTW-elev-0p040.geo > ../outputs/PTW-elev-0p040.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p040.geo'
          rm PTW-elev-0p040.geo

echo ""
echo "time used to run PTW-elev-0p040.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 41 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p041.geo .'
          cp ../inputs/PTW-elev-0p041.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p041.geo > ../outputs/PTW-elev-0p041.out'
          ./MMoM_4.1.12 PTW-elev-0p041.geo > ../outputs/PTW-elev-0p041.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p041.geo'
          rm PTW-elev-0p041.geo

echo ""
echo "time used to run PTW-elev-0p041.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 42 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p042.geo .'
          cp ../inputs/PTW-elev-0p042.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p042.geo > ../outputs/PTW-elev-0p042.out'
          ./MMoM_4.1.12 PTW-elev-0p042.geo > ../outputs/PTW-elev-0p042.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p042.geo'
          rm PTW-elev-0p042.geo

echo ""
echo "time used to run PTW-elev-0p042.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 43 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p043.geo .'
          cp ../inputs/PTW-elev-0p043.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p043.geo > ../outputs/PTW-elev-0p043.out'
          ./MMoM_4.1.12 PTW-elev-0p043.geo > ../outputs/PTW-elev-0p043.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p043.geo'
          rm PTW-elev-0p043.geo

echo ""
echo "time used to run PTW-elev-0p043.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 44 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p044.geo .'
          cp ../inputs/PTW-elev-0p044.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p044.geo > ../outputs/PTW-elev-0p044.out'
          ./MMoM_4.1.12 PTW-elev-0p044.geo > ../outputs/PTW-elev-0p044.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p044.geo'
          rm PTW-elev-0p044.geo

echo ""
echo "time used to run PTW-elev-0p044.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 45 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p045.geo .'
          cp ../inputs/PTW-elev-0p045.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p045.geo > ../outputs/PTW-elev-0p045.out'
          ./MMoM_4.1.12 PTW-elev-0p045.geo > ../outputs/PTW-elev-0p045.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p045.geo'
          rm PTW-elev-0p045.geo

echo ""
echo "time used to run PTW-elev-0p045.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 46 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p046.geo .'
          cp ../inputs/PTW-elev-0p046.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p046.geo > ../outputs/PTW-elev-0p046.out'
          ./MMoM_4.1.12 PTW-elev-0p046.geo > ../outputs/PTW-elev-0p046.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p046.geo'
          rm PTW-elev-0p046.geo

echo ""
echo "time used to run PTW-elev-0p046.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 47 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p047.geo .'
          cp ../inputs/PTW-elev-0p047.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p047.geo > ../outputs/PTW-elev-0p047.out'
          ./MMoM_4.1.12 PTW-elev-0p047.geo > ../outputs/PTW-elev-0p047.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p047.geo'
          rm PTW-elev-0p047.geo

echo ""
echo "time used to run PTW-elev-0p047.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 48 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p048.geo .'
          cp ../inputs/PTW-elev-0p048.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p048.geo > ../outputs/PTW-elev-0p048.out'
          ./MMoM_4.1.12 PTW-elev-0p048.geo > ../outputs/PTW-elev-0p048.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p048.geo'
          rm PTW-elev-0p048.geo

echo ""
echo "time used to run PTW-elev-0p048.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 49 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p049.geo .'
          cp ../inputs/PTW-elev-0p049.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p049.geo > ../outputs/PTW-elev-0p049.out'
          ./MMoM_4.1.12 PTW-elev-0p049.geo > ../outputs/PTW-elev-0p049.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p049.geo'
          rm PTW-elev-0p049.geo

echo ""
echo "time used to run PTW-elev-0p049.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 50 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p050.geo .'
          cp ../inputs/PTW-elev-0p050.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p050.geo > ../outputs/PTW-elev-0p050.out'
          ./MMoM_4.1.12 PTW-elev-0p050.geo > ../outputs/PTW-elev-0p050.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p050.geo'
          rm PTW-elev-0p050.geo

echo ""
echo "time used to run PTW-elev-0p050.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 51 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p051.geo .'
          cp ../inputs/PTW-elev-0p051.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p051.geo > ../outputs/PTW-elev-0p051.out'
          ./MMoM_4.1.12 PTW-elev-0p051.geo > ../outputs/PTW-elev-0p051.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p051.geo'
          rm PTW-elev-0p051.geo

echo ""
echo "time used to run PTW-elev-0p051.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 52 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p052.geo .'
          cp ../inputs/PTW-elev-0p052.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p052.geo > ../outputs/PTW-elev-0p052.out'
          ./MMoM_4.1.12 PTW-elev-0p052.geo > ../outputs/PTW-elev-0p052.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p052.geo'
          rm PTW-elev-0p052.geo

echo ""
echo "time used to run PTW-elev-0p052.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 53 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p053.geo .'
          cp ../inputs/PTW-elev-0p053.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p053.geo > ../outputs/PTW-elev-0p053.out'
          ./MMoM_4.1.12 PTW-elev-0p053.geo > ../outputs/PTW-elev-0p053.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p053.geo'
          rm PTW-elev-0p053.geo

echo ""
echo "time used to run PTW-elev-0p053.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 54 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p054.geo .'
          cp ../inputs/PTW-elev-0p054.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p054.geo > ../outputs/PTW-elev-0p054.out'
          ./MMoM_4.1.12 PTW-elev-0p054.geo > ../outputs/PTW-elev-0p054.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p054.geo'
          rm PTW-elev-0p054.geo

echo ""
echo "time used to run PTW-elev-0p054.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 55 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p055.geo .'
          cp ../inputs/PTW-elev-0p055.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p055.geo > ../outputs/PTW-elev-0p055.out'
          ./MMoM_4.1.12 PTW-elev-0p055.geo > ../outputs/PTW-elev-0p055.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p055.geo'
          rm PTW-elev-0p055.geo

echo ""
echo "time used to run PTW-elev-0p055.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 56 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p056.geo .'
          cp ../inputs/PTW-elev-0p056.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p056.geo > ../outputs/PTW-elev-0p056.out'
          ./MMoM_4.1.12 PTW-elev-0p056.geo > ../outputs/PTW-elev-0p056.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p056.geo'
          rm PTW-elev-0p056.geo

echo ""
echo "time used to run PTW-elev-0p056.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 57 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p057.geo .'
          cp ../inputs/PTW-elev-0p057.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p057.geo > ../outputs/PTW-elev-0p057.out'
          ./MMoM_4.1.12 PTW-elev-0p057.geo > ../outputs/PTW-elev-0p057.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p057.geo'
          rm PTW-elev-0p057.geo

echo ""
echo "time used to run PTW-elev-0p057.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 58 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p058.geo .'
          cp ../inputs/PTW-elev-0p058.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p058.geo > ../outputs/PTW-elev-0p058.out'
          ./MMoM_4.1.12 PTW-elev-0p058.geo > ../outputs/PTW-elev-0p058.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p058.geo'
          rm PTW-elev-0p058.geo

echo ""
echo "time used to run PTW-elev-0p058.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 59 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p059.geo .'
          cp ../inputs/PTW-elev-0p059.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p059.geo > ../outputs/PTW-elev-0p059.out'
          ./MMoM_4.1.12 PTW-elev-0p059.geo > ../outputs/PTW-elev-0p059.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p059.geo'
          rm PTW-elev-0p059.geo

echo ""
echo "time used to run PTW-elev-0p059.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 60 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p060.geo .'
          cp ../inputs/PTW-elev-0p060.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p060.geo > ../outputs/PTW-elev-0p060.out'
          ./MMoM_4.1.12 PTW-elev-0p060.geo > ../outputs/PTW-elev-0p060.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p060.geo'
          rm PTW-elev-0p060.geo

echo ""
echo "time used to run PTW-elev-0p060.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 61 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p061.geo .'
          cp ../inputs/PTW-elev-0p061.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p061.geo > ../outputs/PTW-elev-0p061.out'
          ./MMoM_4.1.12 PTW-elev-0p061.geo > ../outputs/PTW-elev-0p061.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p061.geo'
          rm PTW-elev-0p061.geo

echo ""
echo "time used to run PTW-elev-0p061.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 62 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p062.geo .'
          cp ../inputs/PTW-elev-0p062.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p062.geo > ../outputs/PTW-elev-0p062.out'
          ./MMoM_4.1.12 PTW-elev-0p062.geo > ../outputs/PTW-elev-0p062.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p062.geo'
          rm PTW-elev-0p062.geo

echo ""
echo "time used to run PTW-elev-0p062.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 63 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p063.geo .'
          cp ../inputs/PTW-elev-0p063.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p063.geo > ../outputs/PTW-elev-0p063.out'
          ./MMoM_4.1.12 PTW-elev-0p063.geo > ../outputs/PTW-elev-0p063.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p063.geo'
          rm PTW-elev-0p063.geo

echo ""
echo "time used to run PTW-elev-0p063.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 64 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p064.geo .'
          cp ../inputs/PTW-elev-0p064.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p064.geo > ../outputs/PTW-elev-0p064.out'
          ./MMoM_4.1.12 PTW-elev-0p064.geo > ../outputs/PTW-elev-0p064.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p064.geo'
          rm PTW-elev-0p064.geo

echo ""
echo "time used to run PTW-elev-0p064.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 65 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p065.geo .'
          cp ../inputs/PTW-elev-0p065.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p065.geo > ../outputs/PTW-elev-0p065.out'
          ./MMoM_4.1.12 PTW-elev-0p065.geo > ../outputs/PTW-elev-0p065.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p065.geo'
          rm PTW-elev-0p065.geo

echo ""
echo "time used to run PTW-elev-0p065.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 66 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p066.geo .'
          cp ../inputs/PTW-elev-0p066.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p066.geo > ../outputs/PTW-elev-0p066.out'
          ./MMoM_4.1.12 PTW-elev-0p066.geo > ../outputs/PTW-elev-0p066.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p066.geo'
          rm PTW-elev-0p066.geo

echo ""
echo "time used to run PTW-elev-0p066.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 67 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p067.geo .'
          cp ../inputs/PTW-elev-0p067.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p067.geo > ../outputs/PTW-elev-0p067.out'
          ./MMoM_4.1.12 PTW-elev-0p067.geo > ../outputs/PTW-elev-0p067.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p067.geo'
          rm PTW-elev-0p067.geo

echo ""
echo "time used to run PTW-elev-0p067.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 68 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p068.geo .'
          cp ../inputs/PTW-elev-0p068.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p068.geo > ../outputs/PTW-elev-0p068.out'
          ./MMoM_4.1.12 PTW-elev-0p068.geo > ../outputs/PTW-elev-0p068.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p068.geo'
          rm PTW-elev-0p068.geo

echo ""
echo "time used to run PTW-elev-0p068.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 69 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p069.geo .'
          cp ../inputs/PTW-elev-0p069.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p069.geo > ../outputs/PTW-elev-0p069.out'
          ./MMoM_4.1.12 PTW-elev-0p069.geo > ../outputs/PTW-elev-0p069.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p069.geo'
          rm PTW-elev-0p069.geo

echo ""
echo "time used to run PTW-elev-0p069.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 70 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p070.geo .'
          cp ../inputs/PTW-elev-0p070.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p070.geo > ../outputs/PTW-elev-0p070.out'
          ./MMoM_4.1.12 PTW-elev-0p070.geo > ../outputs/PTW-elev-0p070.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p070.geo'
          rm PTW-elev-0p070.geo

echo ""
echo "time used to run PTW-elev-0p070.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 71 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p071.geo .'
          cp ../inputs/PTW-elev-0p071.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p071.geo > ../outputs/PTW-elev-0p071.out'
          ./MMoM_4.1.12 PTW-elev-0p071.geo > ../outputs/PTW-elev-0p071.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p071.geo'
          rm PTW-elev-0p071.geo

echo ""
echo "time used to run PTW-elev-0p071.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 72 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p072.geo .'
          cp ../inputs/PTW-elev-0p072.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p072.geo > ../outputs/PTW-elev-0p072.out'
          ./MMoM_4.1.12 PTW-elev-0p072.geo > ../outputs/PTW-elev-0p072.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p072.geo'
          rm PTW-elev-0p072.geo

echo ""
echo "time used to run PTW-elev-0p072.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 73 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p073.geo .'
          cp ../inputs/PTW-elev-0p073.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p073.geo > ../outputs/PTW-elev-0p073.out'
          ./MMoM_4.1.12 PTW-elev-0p073.geo > ../outputs/PTW-elev-0p073.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p073.geo'
          rm PTW-elev-0p073.geo

echo ""
echo "time used to run PTW-elev-0p073.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 74 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p074.geo .'
          cp ../inputs/PTW-elev-0p074.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p074.geo > ../outputs/PTW-elev-0p074.out'
          ./MMoM_4.1.12 PTW-elev-0p074.geo > ../outputs/PTW-elev-0p074.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p074.geo'
          rm PTW-elev-0p074.geo

echo ""
echo "time used to run PTW-elev-0p074.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 75 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p075.geo .'
          cp ../inputs/PTW-elev-0p075.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p075.geo > ../outputs/PTW-elev-0p075.out'
          ./MMoM_4.1.12 PTW-elev-0p075.geo > ../outputs/PTW-elev-0p075.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p075.geo'
          rm PTW-elev-0p075.geo

echo ""
echo "time used to run PTW-elev-0p075.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 76 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p076.geo .'
          cp ../inputs/PTW-elev-0p076.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p076.geo > ../outputs/PTW-elev-0p076.out'
          ./MMoM_4.1.12 PTW-elev-0p076.geo > ../outputs/PTW-elev-0p076.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p076.geo'
          rm PTW-elev-0p076.geo

echo ""
echo "time used to run PTW-elev-0p076.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 77 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p077.geo .'
          cp ../inputs/PTW-elev-0p077.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p077.geo > ../outputs/PTW-elev-0p077.out'
          ./MMoM_4.1.12 PTW-elev-0p077.geo > ../outputs/PTW-elev-0p077.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p077.geo'
          rm PTW-elev-0p077.geo

echo ""
echo "time used to run PTW-elev-0p077.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 78 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p078.geo .'
          cp ../inputs/PTW-elev-0p078.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p078.geo > ../outputs/PTW-elev-0p078.out'
          ./MMoM_4.1.12 PTW-elev-0p078.geo > ../outputs/PTW-elev-0p078.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p078.geo'
          rm PTW-elev-0p078.geo

echo ""
echo "time used to run PTW-elev-0p078.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 79 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p079.geo .'
          cp ../inputs/PTW-elev-0p079.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p079.geo > ../outputs/PTW-elev-0p079.out'
          ./MMoM_4.1.12 PTW-elev-0p079.geo > ../outputs/PTW-elev-0p079.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p079.geo'
          rm PTW-elev-0p079.geo

echo ""
echo "time used to run PTW-elev-0p079.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 80 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p080.geo .'
          cp ../inputs/PTW-elev-0p080.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p080.geo > ../outputs/PTW-elev-0p080.out'
          ./MMoM_4.1.12 PTW-elev-0p080.geo > ../outputs/PTW-elev-0p080.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p080.geo'
          rm PTW-elev-0p080.geo

echo ""
echo "time used to run PTW-elev-0p080.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 81 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p081.geo .'
          cp ../inputs/PTW-elev-0p081.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p081.geo > ../outputs/PTW-elev-0p081.out'
          ./MMoM_4.1.12 PTW-elev-0p081.geo > ../outputs/PTW-elev-0p081.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p081.geo'
          rm PTW-elev-0p081.geo

echo ""
echo "time used to run PTW-elev-0p081.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 82 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p082.geo .'
          cp ../inputs/PTW-elev-0p082.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p082.geo > ../outputs/PTW-elev-0p082.out'
          ./MMoM_4.1.12 PTW-elev-0p082.geo > ../outputs/PTW-elev-0p082.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p082.geo'
          rm PTW-elev-0p082.geo

echo ""
echo "time used to run PTW-elev-0p082.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 83 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p083.geo .'
          cp ../inputs/PTW-elev-0p083.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p083.geo > ../outputs/PTW-elev-0p083.out'
          ./MMoM_4.1.12 PTW-elev-0p083.geo > ../outputs/PTW-elev-0p083.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p083.geo'
          rm PTW-elev-0p083.geo

echo ""
echo "time used to run PTW-elev-0p083.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 84 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p084.geo .'
          cp ../inputs/PTW-elev-0p084.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p084.geo > ../outputs/PTW-elev-0p084.out'
          ./MMoM_4.1.12 PTW-elev-0p084.geo > ../outputs/PTW-elev-0p084.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p084.geo'
          rm PTW-elev-0p084.geo

echo ""
echo "time used to run PTW-elev-0p084.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 85 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p085.geo .'
          cp ../inputs/PTW-elev-0p085.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p085.geo > ../outputs/PTW-elev-0p085.out'
          ./MMoM_4.1.12 PTW-elev-0p085.geo > ../outputs/PTW-elev-0p085.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p085.geo'
          rm PTW-elev-0p085.geo

echo ""
echo "time used to run PTW-elev-0p085.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 86 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p086.geo .'
          cp ../inputs/PTW-elev-0p086.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p086.geo > ../outputs/PTW-elev-0p086.out'
          ./MMoM_4.1.12 PTW-elev-0p086.geo > ../outputs/PTW-elev-0p086.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p086.geo'
          rm PTW-elev-0p086.geo

echo ""
echo "time used to run PTW-elev-0p086.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 87 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p087.geo .'
          cp ../inputs/PTW-elev-0p087.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p087.geo > ../outputs/PTW-elev-0p087.out'
          ./MMoM_4.1.12 PTW-elev-0p087.geo > ../outputs/PTW-elev-0p087.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p087.geo'
          rm PTW-elev-0p087.geo

echo ""
echo "time used to run PTW-elev-0p087.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 88 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p088.geo .'
          cp ../inputs/PTW-elev-0p088.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p088.geo > ../outputs/PTW-elev-0p088.out'
          ./MMoM_4.1.12 PTW-elev-0p088.geo > ../outputs/PTW-elev-0p088.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p088.geo'
          rm PTW-elev-0p088.geo

echo ""
echo "time used to run PTW-elev-0p088.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 89 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p089.geo .'
          cp ../inputs/PTW-elev-0p089.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p089.geo > ../outputs/PTW-elev-0p089.out'
          ./MMoM_4.1.12 PTW-elev-0p089.geo > ../outputs/PTW-elev-0p089.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p089.geo'
          rm PTW-elev-0p089.geo

echo ""
echo "time used to run PTW-elev-0p089.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 90 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-0p090.geo .'
          cp ../inputs/PTW-elev-0p090.geo .

sub_step './MMoM_4.1.12 PTW-elev-0p090.geo > ../outputs/PTW-elev-0p090.out'
          ./MMoM_4.1.12 PTW-elev-0p090.geo > ../outputs/PTW-elev-0p090.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-0p090.geo'
          rm PTW-elev-0p090.geo

echo ""
echo "time used to run PTW-elev-0p090.geo = $((SECONDS-ticks)) s"

new_step 'clear shared files'
sub_step 'rm PTW-Materials.lib'
          rm PTW-Materials.lib
sub_step 'rm PTW.facet'
          rm PTW.facet
sub_step 'rm -r tempDir/'
          rm -r tempDir/

echo ""
echo "time used = ${SECONDS} s"
date

